export default {
  en: {
    'home.label': 'Home',
    'landing.label': 'Landings',
    'language.label': 'Languages',
    'word.label': 'Words',
    'level.label': 'Levels',
    'user.label': 'Users',
    'sentence.label': 'Sentences',
    'lesson.label': 'Lessons',
  },
  pl: {
    'home.label': 'Strona główna',
    'landing.label': 'Landingi',
    'language.label': 'Języki',
    'word.label': 'Słówka',
    'level.label': 'Poziomy',
    'user.label': 'Użytkownicy',
    'sentence.label': 'Zdania',
    'lesson.label': 'Lekcje',
  },
  pt: {
    'home.label': 'Início',
    'landing.label': 'Landings',
    'language.label': 'Línguas',
    'word.label': 'Palavras',
    'level.label': 'Níveis',
    'user.label': 'Usuários',
    'sentence.label': 'Frases',
    'lesson.label': 'Lições',
  },
};
