export enum WORDGROUP {
  VERB = 'VERB',
  NOUN = 'NOUN',
  ADJECTIVE = 'ADJECTIVE',
  ADVERB = 'ADVERB',
  PRONOUN = 'PRONOUN',
  ARTICLE = 'ARTICLE',
  PREPOSITION = 'PREPOSITION',
  CONJUCTION = 'CONJUCTION',
  NUMERAL = 'NUMERAL'
}
